// src/components/Biography.tsx
const Biography = () => {
  return (
    <>
      <div className="grid md:grid-cols-3 sm:grid-cols-1 gap-4">
        <div className="photo">
          <img
            src="./img/kamal.jpg"
            alt="kamal sahmoud"
            className="opacity-20 rounded-full"
            width="200px"
            height="200px"
          />
          <ul className="mt-4 glitch">
            <li>
              <a href="https://github.com/kamalkech">Linkedin</a>
            </li>
            <li>
              <a href="https://github.com/kamalkech">Github</a>
            </li>
          </ul>
        </div>
        <div className="bioigraphy md:col-span-2">
          <h1
            className="glitch uppercase text-5xl md:mb-8 sm:mb-6"
            id="main-title"
          >
            <span aria-hidden="true">Kamal</span>
            Kamal
            <span aria-hidden="true">Kamal</span>
          </h1>

          <h2 className="glitch normal-case text-2xl tracking-tight font-extrabold sm:text-2xl md:text-2xl">
            A fullstack engineer, auto learn and build different stuff for web
          </h2>
        </div>
      </div>
      <p className="mt-6 glitch text-slate-50 text-sm">
        Hello, i am web developer frontend / backend for more than 10 years,
        currently i am working in a web agency in Rabat. I have acquired
        know-how and solid knowledge in all stages of website creation.
        Autonomous and sociable, i can carry out a solo project as well as
        integrate myself into an already existing team. Flexible on time and
        pace of work, i adapt to meet your needs and minimize your development
        costs. My qualities are good listening / understanding of customer
        needs, seriousness in the realization, advice and decision support
        before development.
      </p>
    </>
  );
};

export default Biography;

// src/lib/Components/Biography.svelte
<!-- Start biography -->
<div class="grid md:grid-cols-3 sm:grid-cols-1 gap-4">
	<div class="photo">
		<img
			src="./img/kamal.jpg"
			alt="kamal sahmoud"
			class="opacity-20 rounded-full"
			width="200px"
			height="200px"
		/>
		<ul class="mt-4 glitch">
			<li>
				<a href="https://github.com/kamalkech">Linkedin</a>
			</li>
			<li><a href="https://github.com/kamalkech">Github</a></li>
		</ul>
	</div>

	<div class="bioigraphy md:col-span-2">
		<h1 class="glitch uppercase text-5xl md:mb-8 sm:mb-6" id="main-title">
			<span aria-hidden="true">Kamal</span>
			Kamal
			<span aria-hidden="true">Kamal</span>
		</h1>

		<h2 class="glitch normal-case text-2xl tracking-tight font-extrabold sm:text-2xl md:text-2xl">
			A fullstack engineer, auto learn and build different stuff for web
		</h2>
	</div>
</div>
<p class="mt-6 glitch text-slate-50 text-sm">
	Hello, i am web developer frontend / backend for more than 10 years, currently i am working in a
	web agency in Rabat. I have acquired know-how and solid knowledge in all stages of website
	creation. Autonomous and sociable, i can carry out a solo project as well as integrate myself into
	an already existing team. Flexible on time and pace of work, i adapt to meet your needs and
	minimize your development costs. My qualities are good listening / understanding of customer
	needs, seriousness in the realization, advice and decision support before development.
</p>
<!-- End biography -->
