// src/components/ContactForm.tsx
import FormContact from "./FormContact";

const ContactForm = () => {
  return (
    <div className="contact glitch mb-6">
      <div className="title-section my-6">
        <h2 className="normal-case text-2xl tracking-tight font-extrabold sm:text-2xl md:text-4xl">
          Contact me
        </h2>
      </div>
      <FormContact />
    </div>
  );
};

export default ContactForm;

// src/lib/Components/ContactForm.svelte
<script lang="ts">
	import FormContact from '$lib/Components/Form.svelte';
</script>

<!-- Start contact form -->
<div class="contact glitch mb-6">
	<div class="title-section my-6">
		<h2 class="normal-case text-2xl tracking-tight font-extrabold sm:text-2xl md:text-4xl">
			Contact me
		</h2>
	</div>
	<FormContact />
</div>
<!-- End contact form-->
